# This file is used to configure the deployment of the Docket Management System on Render.

services:
  - type: web
    name: docket-management-system
    env: python
    plan: free
    buildCommand: "pip install -r Docket-system-backend/requirements.txt"
    startCommand: "gunicorn --workers 4 --bind 0.0.0.0:$PORT Docket-system-backend.app:app"
    envVars:
      - key: HOST
        value: gateway01.ap-northeast-1.prod.aws.tidbcloud.com
      - key: PORT
        value: 4000
      - key: USERNAME
        value: 2wGfoFiLFYb2YT7.root
      - key: PASSWORD
        value: kHwx6CzeHnQmSWNV
      - key: DATABASE
        value: docket_system2
      - key: CA_PATH
        value: Docket-system-backend/isrgrootx1.pem
      - key: DB_PLATFORM
        value: TIDB
      - key: JWT_SECRET
        sync: false
      - key: PYTHONPATH
        value: .

